name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world

  build_skim_latest:
    needs: greeting
    runs-on: ubuntu-latest
    continue-on-error: true
    container: rootproject/root-conda:${{ matrix.version }}
    strategy:
      fail-fast: false
     matrix:
       version: [6.18.04, latest]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: latest
        run: |
          COMPILER=$(root-config --cxx)
          FLAGS=$(root-config --cflags --libs)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS